# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Mod Properties
mod_id = untitledbugmod
mod_name = Untitled Bug Mod
mod_version = 0.0.1a-build.2
mod_description = A lot of cute bugs
mod_license = MIT
mod_authors = JustMili, PolloComun

maven_group = net.justmili.bugs
archives_base_name = UntitledBugMod

minecraft_version_constraint = 26.1.2

# Dependencies
config_lib = 1.0.0+mc26.1.2-Fabric
mod_menu = 18.0.0-beta.1